name: Terraform Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_s3_bucket: ${{ secrets.S3_BUCKET }}
          TF_VAR_s3_key: ${{ secrets.S3_KEY }}
          TF_VAR_s3_region: ${{ secrets.AWS_REGION }}
          TF_VAR_dynamodb_table: ${{ secrets.DYNAMODB_TABLE }}
        run: terraform init

      - name: Plan Terraform
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_s3_bucket: ${{ secrets.S3_BUCKET }}
          TF_VAR_s3_key: ${{ secrets.S3_KEY }}
          TF_VAR_s3_region: ${{ secrets.AWS_REGION }}
          TF_VAR_dynamodb_table: ${{ secrets.DYNAMODB_TABLE }}
        run: terraform plan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_s3_bucket: ${{ secrets.S3_BUCKET }}
          TF_VAR_s3_key: ${{ secrets.S3_KEY }}
          TF_VAR_s3_region: ${{ secrets.AWS_REGION }}
          TF_VAR_dynamodb_table: ${{ secrets.DYNAMODB_TABLE }}
        run: terraform apply -auto-approve

      - name: Apply Terraform on PR Merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_s3_bucket: ${{ secrets.S3_BUCKET }}
          TF_VAR_s3_key: ${{ secrets.S3_KEY }}
          TF_VAR_s3_region: ${{ secrets.AWS_REGION }}
          TF_VAR_dynamodb_table: ${{ secrets.DYNAMODB_TABLE }}
        run: terraform apply -auto-approve
